# Generated by Django 2.1.1 on 2018-10-23 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=2000)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='customDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='customRecipe',
            fields=[
                ('custom_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='drinkRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('drink_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='favoriteDrink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Drink')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('salted_password', models.CharField(max_length=15)),
                ('salt', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='ingredient_list',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
        migrations.AddField(
            model_name='favoritedrink',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
        migrations.AddField(
            model_name='customrecipe',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Ingredient_List'),
        ),
        migrations.AddField(
            model_name='customrecipe',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
        migrations.AddField(
            model_name='customdrink',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Ingredient_List'),
        ),
        migrations.AddField(
            model_name='customdrink',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Drink'),
        ),
        migrations.AddField(
            model_name='customdrink',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='drink_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Drink'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
    ]
