# Generated by Django 2.1.1 on 2018-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkrating',
            name='drink_id',
            field=models.IntegerField(),
        ),
    ]
