# Generated by Django 2.1.1 on 2018-10-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='drink_name',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customdrink',
            old_name='name',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='customdrink',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='customrecipe',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='drinkrating',
            old_name='drink_name',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='favoritedrink',
            old_name='drink_name',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='favoritedrink',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ingredient',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ingredient_list',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='drink',
            name='cocktaildb_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='drinkrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
