# Generated by Django 2.1.3 on 2018-11-29 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
