# Generated by Django 2.1.1 on 2018-10-25 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0002_auto_20181024_0552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkrating',
            old_name='drink',
            new_name='drink_id',
        ),
        migrations.AddField(
            model_name='drinkrating',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
            preserve_default=False,
        ),
    ]
