# Generated by Django 2.1.1 on 2018-12-04 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0003_auto_20181203_1908'),
    ]

    operations = [
        migrations.DeleteModel("customrecipe")
    ]
