# Generated by Django 2.1.1 on 2018-10-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0003_auto_20181025_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='ingredient_list',
            options={'ordering': ['user']},
        ),
        migrations.AddField(
            model_name='ingredient_list',
            name='ingredient',
            field=models.CharField(default='unavailable', max_length=50),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='ingredient_list',
            name='ingredients',
        ),
        migrations.AlterUniqueTogether(
            name='ingredient_list',
            unique_together={('user', 'ingredient')},
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
