# Generated by Django 2.1.1 on 2018-12-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0003_auto_20181203_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedrink',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
    ]
