# Generated by Django 2.1.1 on 2018-10-26 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0003_auto_20181025_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='drink',
            new_name='drinkID',
        ),
    ]
