# Generated by Django 2.1.1 on 2018-10-26 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0004_auto_20181026_1537'),
        ('DrinkBeyondThePossible', '0004_auto_20181026_1847'),
    ]

    operations = [
    ]
