# Generated by Django 2.1.1 on 2018-12-06 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0004_auto_20181206_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdrink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
    ]
