# Generated by Django 2.1.1 on 2018-12-04 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0004_auto_20181203_2038'),
    ]

    operations = [
        migrations.CreateModel(
            name='customRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(max_length=50)),
                ('ingredient', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='customdrink',
            name='drink_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customdrink',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='customdrink',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='customdrink',
            name='ingredients',
        ),
        migrations.AlterUniqueTogether(
            name='customdrink',
            unique_together={('drink_name', 'user')},
        ),
    ]
