# Generated by Django 2.1.1 on 2018-12-07 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0005_auto_20181206_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrecipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
    ]
