# Generated by Django 2.1.1 on 2018-10-26 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0005_merge_20181026_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='drinkID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
    ]
