# Generated by Django 2.1.1 on 2018-12-04 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0005_auto_20181203_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdrink',
            name='instructions',
            field=models.CharField(default='N/A', max_length=2000),
            preserve_default=False,
        ),
    ]
