# Generated by Django 2.1.1 on 2018-10-26 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0006_auto_20181026_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
