# Generated by Django 2.1.1 on 2018-12-05 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0007_auto_20181203_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customdrink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
    ]
