# Generated by Django 2.1.1 on 2018-10-27 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0006_auto_20181026_2051'),
        ('DrinkBeyondThePossible', '0008_auto_20181026_2206'),
    ]

    operations = [
    ]
