# Generated by Django 2.1.1 on 2018-11-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0011_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drink',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='tags',
        ),
        migrations.AddField(
            model_name='tag',
            name='drink_ID',
            field=models.ForeignKey(default=13060, on_delete=False, to='DrinkBeyondThePossible.Drink'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(default=13060, max_length=20),
            preserve_default=False,
        ),
    ]
