# Generated by Django 2.1.1 on 2018-12-07 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0011_auto_20181207_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedrink',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
    ]
