# Generated by Django 2.1.1 on 2018-11-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0012_auto_20181108_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='drink_ID',
            field=models.IntegerField(),
        ),
    ]
