# Generated by Django 2.1.1 on 2018-11-13 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0013_auto_20181108_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customdrink',
            name='tags',
        ),
        migrations.AlterField(
            model_name='drinkrating',
            name='drink_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Drink'),
        ),
        migrations.AlterField(
            model_name='drinkrating',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
