# Generated by Django 2.1.1 on 2018-12-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0013_auto_20181207_0233'),
        ('DrinkBeyondThePossible', '0006_auto_20181207_0117'),
    ]

    operations = [
    ]
