# Generated by Django 2.1.1 on 2018-11-13 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0014_auto_20181113_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritedrink',
            name='drink',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Drink'),
        ),
    ]
