# Generated by Django 2.1.1 on 2018-11-13 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0015_auto_20181113_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrecipe',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
