# Generated by Django 2.1.1 on 2018-11-13 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DrinkBeyondThePossible', '0016_auto_20181113_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customrecipe',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
        migrations.AlterField(
            model_name='drinkrating',
            name='drink_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Drink'),
        ),
        migrations.AlterField(
            model_name='drinkrating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Profile'),
        ),
        migrations.AlterField(
            model_name='favoritedrink',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrinkBeyondThePossible.Drink'),
        ),
    ]
